package de.ws1718.ismla.JapaneseHelper.server.preprocessing;

public enum Inflection {

	// stem forms
	IMPERFECTIVE, CONTINUATIVE, TERMINAL, ATTRIBUTIVE, HYPOTHETICAL, IMPERATIVE, 
	// key constructions (verb + adj)
	FORMAL, VOLITIONAL, CONJUNCTIVE,
	// key constructions (verb)
	PASSIVE, CAUSATIVE, POTENTIAL, NEGATIVE, NEGATIVE_CONTINUATIVE, 
	PERFECTIVE, HYPOTHETICAL_CONDITIONAL,
	// key constructions (adjective)
	INFORMAL_NEGATIVE, INFORMAL_PAST, INFORMAL_NEGATIVE_PAST, 
	FORMAL_NEGATIVE, FORMAL_PAST, FORMAL_NEGATIVE_PAST,
	CONDITIONAL, PROVISIONAL, ADVERBIAL, DEGREE,
	// alternatives
	CAUSATIVE2, CONTINUATIVE2, IMPERARTIVE2, POTENTIAL2, NEGATIVE2, NEGATIVE3, 
	INFORMAL_NEGATIVE2, INFORMAL_NEGATIVE_PAST2, IMPERFECTIVE2, IMPERATIVE2, IMPERATIVE3,
	VOLITIONAL2, HYPOTHETICAL_CONDITIONAL2, PASSIVE2, FORMAL_NEGATIVE2, FORMAL_NEGATIVE_PAST2, 
}
