package de.ws1718.ismla.JapaneseHelper.server.preprocessing;

public enum VerbForm {

	// stem forms
	IMPERFECTIVE, CONTINUATIVE, TERMINAL, ATTRIBUTIVE, HYPOTHETICAL, IMPERATIVE, 
	// key constructions
	PASSIVE, CAUSATIVE, CAUSATIVE2, POTENTIAL, VOLITIONAL, NEGATIVE, NEGATIVE_CONTINUATIVE, 
	FORMAL, PERFECTIVE, CONJUNCTIVE, HYPOTHETICAL_CONDITIONAL,

}
